apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
spec:
  selector:
    app: simple-web-app
  ports:
  - protocol: TCP
    port: 80          # Порт, который будет доступен внутри кластера
    targetPort: 5000  # Порт контейнера
  type: NodePort      # Делаем приложение доступным снаружи кластера
